### ISSUE TITLE
server icon spacing,check mark, and image transparency

### ISSUE THREAD

**Issue by Gavintime** [AccraZed/YoRHA-UI-BetterDiscord#5]
Servers underneath open folders aren't pushed down enough causing the folder and the server below to overlap a bit. Also when uploading images, the check mark for the spoiler option is shown for both enabled and disabled. Lastly, all images in chat have a slight transparency to them, not sure if this is intentional.

**Comment by AccraZed** [comment]
I think I fixed the server folder problem and the spoiler problem (although every time I fix something on one place something else breaks in another reeeeee), and images appear that way because the lattice effect overlays the entire application (along with the vignette effect). if you want to turn off the lattice, you can type `#app-mount:after { visibility:hidden; }` into the custom CSS thing for better discord

**Comment by Gavintime** [comment]
since the update, open folders no longer expand far enough, causing the last server in the folder to go past the folder outline, also the last server in the folder now slightly touches the next server
