### ISSUE TITLE
Name display issue inside of servers, channels, and dms

### ISSUE THREAD

**Issue by The-Scout** [AccraZed/YoRHA-UI-BetterDiscord#57]
Names are getting double layered.  https://i.imgur.com/Io0Kn2o.png https://i.imgur.com/H9xWFue.png

**Comment by AccraZed** [comment]
This is intentional, meant to mimic the text used to title a lot of things in automata. Although, it seems like the text you're using is darker than it should be for the dark theme? 
![image](https://user-images.githubusercontent.com/8460982/133862103-93eac6f6-12a2-4e33-a36d-1f0e6f3acfcc.png)
This is how it ought to look. If you have further issues you can re-open the issue c:

**Comment by The-Scout** [comment]
ah makes sense, and yes i modified the colors abit on my copy
